// Generated by CoffeeScript 1.3.3

$(document).ready(function() {
  $(".playlist").addClass("closed hidden transition transition-height");
  return $(".cover-picker").on("click", "a", function(event) {
    var albumSelected, canvas, coverActive, coverAnchor, coverSelected, image, indicatorPosition, playlistHeight, switchPlaylistToAlbum, togglePlaylistForAlbum,
      _this = this;
    coverAnchor = this;
    coverSelected = coverAnchor.parentNode;
    coverActive = $(".cover-picker .active");
    albumSelected = coverAnchor.href.replace("#", "");
    indicatorPosition = coverSelected.offsetLeft + (coverSelected.offsetWidth / 2) - 15;
    playlistHeight = $(".playlist-inner")[0].getBoundingClientRect().height;
    togglePlaylistForAlbum = function(album) {
      var isExpanding, targetHeight;
      isExpanding = $(".playlist").hasClass("closed");
      targetHeight = isExpanding ? 400 : 0;
      if (isExpanding) {
        $(".playlist").removeClass("hidden");
        $(".playlist-indicator").removeClass("hidden").css("left", indicatorPosition);
      } else {
        $(".playlist").on("webkitTransitionEnd", function() {
          $(".playlist-indicator").addClass("hidden");
          return $(".playlist").addClass("hidden").off("webkitTransitionEnd");
        });
      }
      $(coverSelected).toggleClass("active");
      return $(".playlist").toggleClass("closed expanded").height(targetHeight);
    };
    switchPlaylistToAlbum = function(album) {
      $(coverActive).removeClass("active");
      $(coverSelected).addClass("active");
      return $(".playlist-indicator").css("left", indicatorPosition);
    };
    if (($(coverActive).length === 0) || (coverSelected === coverActive[0])) {
      togglePlaylistForAlbum(albumSelected);
    } else if ($(coverActive).length > 0) {
      switchPlaylistToAlbum(albumSelected);
    }
    coverAnchor.blur();
    event.preventDefault();
    canvas = document.getElementById("album-artwork");
    image = new Image;
    image.src = coverAnchor.childNodes[0].src;
    return ColorTunes.launch(image, canvas);
  });
});
